import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createInterface } from 'node:readline/promises';

/**
 * Generates the secrets a deployment needs, once.
 *
 *     npm run gen:secrets
 *
 * They are written to `.env.production.local`, which is git-ignored, and
 * printed in the form the host's bulk environment-variable paste accepts. The
 * four values that come from Supabase are left blank for you to fill in.
 *
 * Nothing leaves this machine. Generating them here rather than in a chat
 * window, a document or an email is the point: a secret that has been pasted
 * somewhere it can be read later is not a secret any more.
 */

const TARGET = resolve(process.cwd(), '.env.production.local');

/** 48 bytes for the signing key, 32 for the AES-256 key, which must be exact. */
const secret = (bytes: number) => randomBytes(bytes).toString('base64');

function build(): string {
  return `# Generated by \`npm run gen:secrets\` on ${new Date().toISOString().slice(0, 10)}.
# This file is git-ignored. Do not commit it, paste it into a chat, or email it.
#
# Paste everything below into the host's environment variables. On Netlify:
# Site configuration -> Environment variables -> Add a variable -> Import from
# a .env file, then paste. Fill in the four Supabase values first.

# --- generated here; nothing else needs to know them ------------------------
AUTH_SECRET=${secret(48)}
ENCRYPTION_KEY=${secret(32)}
CRON_SECRET=${secret(32)}

# --- from Supabase ----------------------------------------------------------
# Settings -> Database -> Connection pooling (the POOLER string, not the direct
# one: a serverless host opens many short-lived connections and will exhaust a
# direct connection). Append ?sslmode=require if it is not already there.
DATABASE_URL=

# Settings -> API -> Project URL
SUPABASE_URL=
# Settings -> API -> service_role key (NOT the anon key)
SUPABASE_SERVICE_ROLE_KEY=
# Storage -> create a private bucket with this name
SUPABASE_STORAGE_BUCKET=command-center
STORAGE_DRIVER=supabase

# --- the site itself --------------------------------------------------------
# Your Netlify URL, once you know it. Links in notifications use this.
APP_URL=

# Demo data has no place on a deployment. netlify.toml sets these too; they are
# repeated here so \`npm run check:deploy\` sees the same configuration.
DEMO_MODE=false
DISABLE_DEMO_DATA=true
`;
}

async function main() {
  if (existsSync(TARGET)) {
    const existing = readFileSync(TARGET, 'utf8');
    const hasSecrets = /AUTH_SECRET=\S/.test(existing);
    if (hasSecrets) {
      console.log(`\n${TARGET} already exists and has secrets in it.`);
      console.log('Rewriting it would invalidate every session and make every stored');
      console.log('integration credential undecryptable on a deployment already using them.\n');

      if (!process.stdin.isTTY) {
        console.log('Delete the file yourself if you are sure you want new ones.');
        process.exit(1);
      }
      const rl = createInterface({ input: process.stdin, output: process.stdout });
      const answer = await rl.question('Type "replace" to generate new ones anyway: ');
      rl.close();
      if (answer.trim() !== 'replace') {
        console.log('Left alone.');
        process.exit(0);
      }
    }
  }

  const body = build();
  writeFileSync(TARGET, body, { mode: 0o600 });

  console.log(`\nWritten to ${TARGET} (readable only by you, and git-ignored).\n`);
  console.log('─'.repeat(70));
  console.log(body.trimEnd());
  console.log('─'.repeat(70));
  console.log(`
Next:
  1. Fill in the blank values from Supabase and your Netlify URL.
  2. Check it:            npm run check:deploy
  3. Paste it into Netlify's environment variables.

Keep a copy in a password manager. If ENCRYPTION_KEY is lost, stored
integration credentials cannot be decrypted; if AUTH_SECRET is lost, everyone
is signed out. Neither is recoverable from the database.
`);
}

main().catch((err) => {
  console.error('Could not generate secrets:', err);
  process.exit(1);
});
