'use client';
import * as React from 'react';
import Link from 'next/link';
import { toast } from 'sonner';
import { ArrowUp, Info, Loader2, Quote, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { askKnowledgeAction } from '@/server/actions/knowledge';
import { titleCase, truncate } from '@/lib/utils';

interface Citation {
  index: number;
  sourceType: string;
  sourceId: string;
  title: string;
  href: string | null;
  excerpt: string;
}

interface Answer {
  question: string;
  answer: string;
  citations: Citation[];
  insufficient: boolean;
  provider: string;
  model: string;
  sourcesConsidered: number;
  includesDemoData: boolean;
}

export function KnowledgeAssistant({
  suggestions,
  companySlug,
  scopeLabel,
  providerNote,
}: {
  suggestions: readonly string[];
  companySlug: string;
  scopeLabel: string;
  providerNote: string;
}) {
  const [question, setQuestion] = React.useState('');
  const [pending, setPending] = React.useState(false);
  const [history, setHistory] = React.useState<Answer[]>([]);

  const ask = async (text: string) => {
    if (text.trim().length < 4) return;
    setPending(true);
    const result = await askKnowledgeAction({ question: text, companySlug });
    setPending(false);
    if (!result.ok) {
      toast.error(result.error);
      return;
    }
    setHistory((prev) => [{ question: text, ...result.data }, ...prev]);
    setQuestion('');
  };

  return (
    <div className="grid grid-cols-1 gap-5 lg:grid-cols-[1fr_18rem]">
      <div className="min-w-0 space-y-4">
        <Card>
          <CardContent className="pt-5">
            <form
              onSubmit={(e) => {
                e.preventDefault();
                void ask(question);
              }}
              className="space-y-3"
            >
              <Textarea
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
                    e.preventDefault();
                    void ask(question);
                  }
                }}
                rows={3}
                placeholder={`Ask about anything in ${scopeLabel}. For example: which clients have unpaid invoices?`}
                aria-label="Your question"
              />
              <div className="flex flex-wrap items-center justify-between gap-2">
                <p className="text-xs text-[var(--fg-subtle)]">⌘/Ctrl + Enter to ask</p>
                <Button type="submit" variant="primary" loading={pending} disabled={question.trim().length < 4}>
                  <ArrowUp /> Ask
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>

        {pending ? (
          <Card>
            <CardContent className="flex items-center gap-2 py-6 text-sm text-[var(--fg-muted)]">
              <Loader2 className="size-4 animate-spin" /> Searching your records…
            </CardContent>
          </Card>
        ) : null}

        {history.length === 0 && !pending ? (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="size-4 text-[var(--gold)]" /> Try one of these
              </CardTitle>
            </CardHeader>
            <CardContent className="flex flex-wrap gap-2">
              {suggestions.map((s) => (
                <button
                  key={s}
                  type="button"
                  onClick={() => void ask(s)}
                  className="rounded-full border border-[var(--border-strong)] px-3 py-1.5 text-sm text-[var(--fg-muted)] transition-colors hover:border-[var(--accent)] hover:text-[var(--accent)]"
                >
                  {s}
                </button>
              ))}
            </CardContent>
          </Card>
        ) : null}

        {history.map((entry, i) => (
          <Card key={`${entry.question}-${i}`}>
            <CardHeader className="pb-2">
              <CardTitle className="text-base">{entry.question}</CardTitle>
              <div className="flex flex-wrap items-center gap-1.5">
                <Badge tone="outline">
                  {entry.provider === 'anthropic' ? 'Generated by Anthropic' : 'Extracted from your records'}
                </Badge>
                <Badge tone="neutral">{entry.sourcesConsidered} source{entry.sourcesConsidered === 1 ? '' : 's'}</Badge>
                {entry.includesDemoData ? <Badge tone="gold">Includes demo data</Badge> : null}
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {entry.insufficient ? (
                <div className="flex items-start gap-2 rounded-lg border border-[var(--warning)]/40 bg-[var(--warning-bg)] px-3 py-2.5 text-sm">
                  <Info className="mt-0.5 size-4 shrink-0 text-[var(--warning)]" />
                  <p>{entry.answer}</p>
                </div>
              ) : (
                <p className="text-sm leading-relaxed whitespace-pre-wrap">{entry.answer}</p>
              )}

              {entry.citations.length ? (
                <div className="space-y-2">
                  <p className="text-[11px] font-semibold tracking-wide text-[var(--fg-subtle)] uppercase">
                    Sources
                  </p>
                  {entry.citations.map((c) => (
                    <div key={`${c.sourceType}-${c.sourceId}`} className="rounded-lg border border-[var(--border)] p-2.5">
                      <div className="flex items-center gap-2">
                        <span className="tnum flex size-5 shrink-0 items-center justify-center rounded bg-[var(--accent-soft)] text-[11px] font-semibold text-[var(--accent-soft-fg)]">
                          {c.index}
                        </span>
                        {c.href ? (
                          <Link href={c.href} className="min-w-0 truncate text-sm font-medium hover:text-[var(--accent)] hover:underline">
                            {c.title}
                          </Link>
                        ) : (
                          <span className="min-w-0 truncate text-sm font-medium">{c.title}</span>
                        )}
                        <Badge tone="outline" className="ml-auto shrink-0">{titleCase(c.sourceType)}</Badge>
                      </div>
                      <p className="mt-1.5 flex gap-1.5 text-xs text-[var(--fg-muted)]">
                        <Quote className="mt-0.5 size-3 shrink-0" />
                        {truncate(c.excerpt, 300)}
                      </p>
                    </div>
                  ))}
                </div>
              ) : null}
            </CardContent>
          </Card>
        ))}
      </div>

      <aside className="space-y-4">
        <Card>
          <CardHeader>
            <CardTitle>How this works</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm text-[var(--fg-muted)]">
            <p>
              Questions are answered only from documents, notes, meetings, clients, partnerships and
              investors that <strong>you</strong> are allowed to read, in <strong>{scopeLabel}</strong>.
            </p>
            <p>
              Every claim carries a citation back to the record it came from. If your records do not
              contain an answer, you get told that rather than a guess.
            </p>
            <p className="border-t border-[var(--border)] pt-2 text-xs">{providerNote}</p>
          </CardContent>
        </Card>
      </aside>
    </div>
  );
}
